name: ci
on:
  push:
    branches:
      - main
      - dev
  pull_request:
env:
  # Default version of Go to use by CI workflows. This should be the latest
  # release of Go; developers likely use the latest release in development and
  # we want to catch any bugs (e.g. lint errors, race detection) with this
  # release before they are merged. The Go compatibility guarantees ensure
  # backwards compatibility with the previous two minor releases and we
  # explicitly test our code for these versions so keeping this at prior
  # versions does not add value.
  DEFAULT_GO_VERSION: "~1.23.0"
jobs:
  test-bench:
    runs-on: riscv-builders
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
          cache-dependency-path: "**/go.sum"
      - name: Run benchmarks to check functionality
        run: make test-bench

  test-bench-qemu:
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
          cache-dependency-path: "**/go.sum"
      - name: Run benchmarks to check functionality Qemu
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: riscv64
          distro: alpine_latest
          run: |
            echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
            echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
            make test-bench
